name: react-theme-utils
on:
  push: {}

jobs:
  lint:
    uses: 'sfusurge/actions-workflows/.github/workflows/npm-lint.yml@v1'
    with:
      workflow-ref: "v1"
      cache-key: "react-theme-utils"
      package: "."

  publish:
    uses: 'sfusurge/actions-workflows/.github/workflows/npm-publish.yml@v1'
    needs: lint
    with:
      workflow-ref: "v1"
      cache-key: "react-theme-utils"
      package: "."
      publish-gpr: ${{ startsWith(github.ref, 'refs/tags/v') }}
      replace-version: "${{ github.ref_name }}"
